spring.main.allow-bean-definition-overriding=true

spring.application.name=smart-interview-coach
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.embedding.model=text-embedding-3-small


#spring.ai.huggingface.chat.api-key=${HUGGINGFACE_API_KEY}
#spring.ai.huggingface.chat.url=https://api-inference.huggingface.co/models/facebook/bart-large-cnn

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distanct-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5434/postgres
spring.datasource.username=postgres

spring.sql.init.mode=always
spring.sql.inti.schema-locations=classpath:schema.sql

spring.jpa.show-sql=true

rag.similarity.search.topk=3