spring.application.name=smart-interview-coach
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini


#spring.ai.huggingface.chat.api-key=${HUGGINGFACE_API_KEY}
#spring.ai.huggingface.chat.url=https://api-inference.huggingface.co/models/facebook/bart-large-cnn